#!/usr/bin/env node

var Parser = require('less').Parser,
    path = require('path'),
    fs = require('fs');

var css_dir = path.join(__dirname, '..', 'public', 'css');

// make sure css directory exists
if (! fs.existsSync(css_dir)) {
  fs.mkdirSync(css_dir);
}

var source = fs.readFileSync(path.join(__dirname, '..', 'less', 'phant.less'), 'utf8');

var parser = new Parser({
  paths: [path.join(__dirname, '..', 'less')]
});

parser.parse(source, function (err, tree) {

  if(err) {
    console.log(err);
    process.exit(1);
  }

  var css = tree.toCSS();

  fs.writeFileSync(path.join(css_dir, 'phant.css'), css, 'utf8');

  var min = tree.toCSS({
    cleancss: true
  });

  fs.writeFileSync(path.join(css_dir, 'phant.min.css'), min, 'utf8');

});
