#!/usr/bin/env node

var httpServer = require('phant-http-server'),
    HttpManager = require('../app'),
    keychain = require('phant-keychain-hex'),
    storage = require('phant-storage-test');

var keys = keychain({
  publicSalt: process.env.PUBLIC_SALT || 'public salt',
  privateSalt: process.env.PRIVATE_SALT || 'private salt'
});

var httpManager = HttpManager({
  storage: storage(),
  keychain: keys
});

// start listening for connections
httpServer.listen(process.env.PORT || 5000);

// attach input to http server
httpServer.use(httpManager);

